version = 0.1
[default.deploy.parameters]
stack_name = "ipv-cri-otg-hmrc-smoke-tests"
resolve_s3 = true
s3_prefix = "ipv-cri-otg-hmrc-smoke-tests"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
