AWSTemplateFormatVersion: "2010-09-09"
Transform: [ AWS::LanguageExtensions, AWS::Serverless-2016-10-31 ]
Description: "Digital Identity IPV CRI Ipv-Cri-OTG-Hmrc-Smoke-Tests API"

Parameters:
  Environment:
    Type: String
    AllowedValues: [ dev, localdev, build, staging, integration, production ]
    ConstraintDescription: must be dev, localdev, build, staging, integration or production
  CodeSigningConfigArn:
    Type: String
    Default: ""
  PermissionsBoundary:
    Type: String
    Default: ""
  OTGStackName:
    Type: String
    Default: otg-hmrc-service
  VpcStackName:
    Type: String
    Default: otg-vpc

Conditions:
  EnforceCodeSigning: !Not [ !Equals [ !Ref CodeSigningConfigArn, "" ] ]
  UsePermissionsBoundary: !Not [!Equals [!Ref PermissionsBoundary, ""]]
  IsDevEnvironment: !Equals [ !Ref Environment, dev ]
  IsLocalDevEnvironment: !Equals [ !Ref Environment, localdev ]
  IsDevLikeEnvironment:
    !Or [ !Condition IsLocalDevEnvironment, !Condition IsDevEnvironment ]
  IsNotDevEnvironment: !Not
    - !Condition IsDevLikeEnvironment

Globals:
  Function:
    Timeout: 30
    CodeUri: ..
    Runtime: nodejs22.x
    Architectures: [ arm64 ]
    PermissionsBoundary:
      !If [UsePermissionsBoundary, !Ref PermissionsBoundary, !Ref AWS::NoValue]

Resources:

  OTGHappyCanaryAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: IsNotDevEnvironment
    Properties:
      AlarmDescription: !Sub Triggers when the ${OTGHappyCanary} canary success percentage is <75 or no data present
      AlarmName: !Sub ${OTGHappyCanary}-canary-failure
      ActionsEnabled: true
      Namespace: CloudWatchSynthetics
      MetricName: SuccessPercent
      ComparisonOperator: LessThanThreshold
      EvaluationPeriods: 1
      Statistic: Average
      Period: 3600
      Threshold: 75
      TreatMissingData: breaching
      OKActions:
        - !ImportValue platform-alarm-warning-alert-topic
      AlarmActions:
        - !ImportValue platform-alarm-warning-alert-topic
      Dimensions:
        - Name: "CanaryName"
          Value: !Ref OTGHappyCanary

  CanariesRole:
    Type: AWS::IAM::Role
    Properties:
      PermissionsBoundary:
        !If [UsePermissionsBoundary, !Ref PermissionsBoundary, !Ref AWS::NoValue]
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service: lambda.amazonaws.com
      Policies:
        - PolicyName: OtgCanariesExecutionRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource: !GetAtt CanariesBucket.Arn
                Action: s3:GetBucketLocation
              - Effect: Allow
                Resource: !Sub ${CanariesBucket.Arn}/*
                Action: s3:PutObject
              - Effect: Allow
                Resource: "*"
                Action:
                  - s3:ListAllMyBuckets
                  - logs:PutLogEvents
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - cloudwatch:PutMetricData
                  - ec2:CreateNetworkInterface
                  - ec2:DescribeNetworkInterfaces
                  - ec2:DeleteNetworkInterface

  CanariesBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  CanaryRunnerFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Sourcemap: true
    Properties:
      Timeout: 60
      Handler: lambdas/canary-runner/src/canary-runner-handler.lambdaHandler
      FunctionName: !Select [3, !Split ["/", !Ref CanaryRunnerFunctionLogGroup]]
      LoggingConfig:
        LogGroup: !Sub /aws/lambda/${AWS::StackName}/CanaryInvokerFunction
      CodeSigningConfigArn:
        !If [ EnforceCodeSigning, !Ref CodeSigningConfigArn, !Ref AWS::NoValue ]
      Policies:
        - Statement:
            Sid: AllowRunCanaries
            Effect: Allow
            Action:
              - synthetics:GetCanary
              - synthetics:StopCanary
              - synthetics:StartCanary
              - synthetics:DescribeCanariesLastRun
            Resource:
              - !Sub arn:aws:synthetics:${AWS::Region}:${AWS::AccountId}:canary:${OTGHappyCanary}

  CanaryRunnerFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${AWS::StackName}-CanaryRunnerFunction
      RetentionInDays: 30

  OTGHappyCanary:
    Type: AWS::Synthetics::Canary
    Properties:
      Name: !Sub ${AWS::StackName}-happy
      StartCanaryAfterCreation: true
      ArtifactS3Location: !Sub s3://${CanariesBucket}/happy
      ExecutionRoleArn: !GetAtt CanariesRole.Arn
      RuntimeVersion: syn-nodejs-puppeteer-7.0
      VPCConfig:
        SecurityGroupIds:
          - !ImportValue otg-vpc-AWSServicesEndpointSecurityGroupId
        SubnetIds:
          - !ImportValue otg-vpc-ProtectedSubnetIdA
          - !ImportValue otg-vpc-ProtectedSubnetIdB
      Schedule:
        Expression: rate(15 minutes)
      Tags:
        - Key: blueprint
          Value: canaryRecorder
        - Key: code location
          Value: ipv-cri-otg-hmrc-smoke-tests
      Code:
        Handler: exports.handler
        Script:
          !Sub
          - |
            const synthetics = require('Synthetics');
            const syntheticsConfiguration = synthetics.getConfiguration();
            const apiCanaryBlueprint = async function () {
              syntheticsConfiguration.setConfig({
                restrictedHeaders: [],
                restrictedUrlParameters: []
              });

              const validateSuccessful = async function(res) {
                return new Promise((resolve, reject) => {
                  if (res.statusCode !== 200) {
                    throw new Error(res.statusCode + ' ' + res.statusMessage);
                  }
                  let responseBody = '';
                  res.on('data', (d) => {
                    responseBody += d;
                  });
                  res.on('end', () => {
                    const body = JSON.parse(responseBody);
                    if (body.token != "goodToken" && body.expiry != "123456") {
                      throw new Error("Unexpected body" + responseBody);
                    }
                    resolve();
                  });
                });
              };
              let requestOptionsStep1 = {
                hostname: '${OtgURL}',
                method: 'GET',
                path: '/${env}/token?tokenType=monitoring',
                port: '443',
                protocol: 'https:',
                body: "",
                headers: {}
              };
              requestOptionsStep1['headers']['User-Agent'] = [synthetics.getCanaryUserAgentString(), requestOptionsStep1['headers']['User-Agent']].join(' ');
              let stepConfig1 = {
                includeRequestHeaders: false,
                includeResponseHeaders: false,
                includeRequestBody: false,
                includeResponseBody: false,
                continueOnHttpStepFailure: true
              };
              await synthetics.executeHttpStep('Verify https://${OtgURL}', requestOptionsStep1, validateSuccessful, stepConfig1);
            };

            exports.handler = async () => {
              return await apiCanaryBlueprint();
            };
          - OtgURL: !Sub
            - "${PrivateApiGatewayId}-${VpceID}.execute-api.eu-west-2.amazonaws.com"
            - PrivateApiGatewayId:
                Fn::ImportValue: !Sub ${OTGStackName}-PrivateApiGatewayId
              VpceID:
                Fn::ImportValue: !Sub ${VpcStackName}-ExecuteApiGatewayEndpointId
            env: !Ref Environment

Outputs:
  CanaryNames:
    Description: The names of the all canaries created by the stack
    Value: !Join
      - ","
      - - !Ref OTGHappyCanary
