name: Package for Dev
on:
  workflow_dispatch:
  push:
    branches: [main]

concurrency:
  group: post-merge-dev
  cancel-in-progress: false

jobs:
  deploy:
    name: Package for Dev
    runs-on: ubuntu-latest
    timeout-minutes: 15
    environment:
      name: development
    env:
      AWS_REGION: eu-west-2
      ENVIRONMENT: dev
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Assume temporary AWS role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.GH_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build SAM app
        uses: govuk-one-login/github-actions/sam/build-application@main
        id: build
        with:
          template: infrastructure/template.yaml
          cache-name: otg-smoke-tests
          pull-repository: false

      - name: Deploy SAM app
        uses: govuk-one-login/devplatform-upload-action@v3.9.2
        with:
          artifact-bucket-name: ${{ vars.ARTIFACT_SOURCE_BUCKET_NAME }}
          signing-profile-name: ${{ vars.SIGNING_PROFILE_NAME }}
          working-directory: .aws-sam/build
